CREATE PROCEDURE LOGIN
    @EMAIL VARCHAR(50),
    @PASSWORD VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM USERS WHERE EMAIL = @EMAIL AND [PASSWORD] = @PASSWORD)
    BEGIN
        UPDATE USERS SET ISLOGGEDIN = 1 WHERE EMAIL = @EMAIL;
        SELECT 'LOGIN SUCCESSFUL' AS MESSAGE, 1 AS ISSUCCESS;
    END
    ELSE
    BEGIN
        SELECT 'INVALID USERNAME OR PASSWORD' AS MESSAGE, 0 AS ISSUCCESS;
    END
END;
GO

--DROP PROCEDURE LOGIN

EXEC LOGIN @EMAIL = 'VISHNU222@GMAIL.COM', @PASSWORD = 'SECRETAGENT';
EXEC LOGIN @EMAIL = 'AMELIEPOULAIN@YAHOO.COM', @PASSWORD = 'SECRETAGENT';

SELECT * FROM USERS;
